### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by DorianMazur** [DorianMazur/WeatherNoAds#1]
- [x] Exiting from App

- [x] Location by IP Adress/GPS

- [x] Some animations and transitions

- [ ] Seperate components
